language: python
python:
 - "2.7"
install:
 - python setup.py sdist --formats=zip -k
 - find ./dist -iname "*.zip" -print0 | xargs -0 pip install
script:
 - python MiiCardConsumers/test/__init__.py
notifications:
  email: false